# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
run:
  timeout: 5m
linters:
  enable:
    - copyloopvar
    - thelper
    - gofumpt
    - bodyclose
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle
    - misspell
    - depguard
    - testifylint
    - gocritic
    - nolintlint
linters-settings:
  gocritic:
    disabled-checks:
      - appendAssign
  staticcheck:
    checks:
      - all
      - "-SA1019"
#  forbidigo:
#    forbid:
#      - 'ioutil\.*'
  tagliatelle:
    case:
      use-field-name: false
      rules:
        yaml: snake
        json: snake
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "use stdlib instead"
          - pkg: "ioutil"
            desc: "请使用io包"
          - pkg: "log"
            desc: "请使用apexlog"
  testifylint:
    enable-all: true
    disable:
      - error-is-as # false positive